"use strict";
const $ = require("jquery");
const fs = require("fs");
var jsonItems = $.getJSON("../../Data/Items.json", function(json) {
  jsonItems =  json;
});
var jsonEvents = $.getJSON("../../Data/Events.json", function(json) {
  jsonEvents =  json;
});
var changedJsonEvents = {};
const easy = ["treasure", "key"];
const normal = ["treasureTwo", "keyTwo1", "keyTwo2"];
const hard = ["treasureThree", "keyThree1", "keyThree2", "keyThree3"];
var rooms = ["goblin", "chest", "randomTrap", "merchant", "lab", "riddle", "nap", "daedalus", "teleporter", "booty", "math"];
var traps = ["boulder", "pitfall"];
var jsonSettings;
var jsonStats;
var startCountingEvents = 0;
var difficulty;
var defaultSize;
var events;
var itemEvents;
var useItemEvents;
var nameGen;
var allGenNames = [];
var attEvents;
var defEvents;
var questionAnswer;
var draggable = false;
var draggableItem = false;
var deze;
var startX;
var startY;
var prevM = "";
var prevA = "";
var prevX;
var prevY;
var attackAmount;
var deadGobPotTry;
var justMageIssues = 0;
var merchantTypeId;
var merchantList = {};
var correctProblem;
var answerProblem;
var answerProblem1;
var answerProblem2;
var askProblem;
var cancelableTimer;
var cancelNextFunction = 0;
var inside = 0;
var inputSize;
var size;
var visibleWidth;
var visibleHeight;
var rowsStart;
var cellsStart;
var autoWidth;
var player;
var minotaur;
var labyrinth = {
  width: undefined,
  height: undefined
};
var rowsNr;
var prevRowsNr = 101;
var prev2RowsNr = 102;
var prev3RowsNr = 103;
var prev4RowsNr = 104;
var cellsNr;
var prevCellsNr = 101;
var prev2CellsNr = 102;
var prev3CellsNr = 103;
var prev4CellsNr = 104;
var newEventLocation;
